---
- hosts: boxes
  connection: local
  gather_facts: no 
   
  tasks: 
   - name: Replace Configs
     napalm_install_config:
#        provider: "{{ creds }}"
        dev_os: ios
        config_file: CONFIGS/{{ inventory_hostname }}.txt
        commit_changes: False
        replace_config: False
        get_diffs: True 
        diff_file: DIFFS/{{ inventory_hostname }}.txt
        optional_args: {'port':"2222"}
        
